// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetTasks():Promise<Array<main.Task>>;

export function LoadTasks():Promise<void>;

export function RemoveTask(arg1:number):Promise<void>;

export function SaveTasks():Promise<void>;

export function ToggleTaskCompletion(arg1:number):Promise<void>;
