// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3) {
  return window['go']['main']['TodoApp']['AddTask'](arg1, arg2, arg3);
}

export function GetTasks() {
  return window['go']['main']['TodoApp']['GetTasks']();
}

export function LoadTasks() {
  return window['go']['main']['TodoApp']['LoadTasks']();
}

export function RemoveTask(arg1) {
  return window['go']['main']['TodoApp']['RemoveTask'](arg1);
}

export function SaveTasks() {
  return window['go']['main']['TodoApp']['SaveTasks']();
}

export function ToggleTaskCompletion(arg1) {
  return window['go']['main']['TodoApp']['ToggleTaskCompletion'](arg1);
}
